### ISSUE TITLE
3D mesh export

### ISSUE THREAD

**Issue by DanieleMagri** [VladimirYugay/Gaussian-SLAM#13]
Is it possible to export the 3D mesh of a scene?

**Comment by VladimirYugay** [comment]
yes, we actually compute the mesh at the end of our algorithm to evaluate how well can we render novel depth map views and how good our reconstruction is.

How exactly we do it, check [here](https://github.com/VladimirYugay/Gaussian-SLAM/blob/5c92d201ae8ad6f2093135419d76d7aaf00d65ce/src/evaluation/evaluator.py#L151).

**Comment by Atticuszz** [comment]
thanks！
