### ISSUE TITLE
Visualization of 3D Gaussians

### ISSUE THREAD

**Issue by robofar** [VladimirYugay/Gaussian-SLAM#18]
How could I visualize 3D Gaussians themselves - I mean scene represented with 3D Gaussians? Is there any script or some package that can do it? That would be useful for seeing how 3D Gaussians actually look like. Thank you

**Comment by VladimirYugay** [comment]
Thanks for your interest!

 Sure, for the visualization and for creating the demo we use this [lib](https://github.com/yzslab/gaussian-splatting-lightning).

**Comment by robofar** [comment]
Thanks!
