### ISSUE TITLE
code release date

### ISSUE THREAD

**Issue by hardikdava** [VladimirYugay/Gaussian-SLAM#2]
@VladimirYugay Great work. This looks promissing. Do you have any plan to release code or any ETA date?

**Comment by VladimirYugay** [comment]
Hey there, thanks for your interest! 

Yes, we do plan to release it. The code is ready to be released, but we didn't get the green light to publish it from the organization that funds our lab yet. We update the README for the ETA.

**Comment by hardikdava** [comment]
Thank you very much for your reply. Can't wait to test it. :)

**Comment by jeezrick** [comment]
Really looking forward for the code too.

**Comment by VladimirYugay** [comment]
Code release!
