### ISSUE TITLE
Help! Reconstruction Performance on Splatam & Gaussian-SLAM

### ISSUE THREAD

**Issue by lif314** [VladimirYugay/Gaussian-SLAM#27]
Thank you for your work! I noticed in Table 7 you reported the reconstruction performance of Splatam on Replica. I need help reproducing this test. Since SplatAM builds meshes using relative poses while Gaussian-SLAM uses absolute poses (aligned with ground truth meshes), the mesh constructed by SplatAM does not align with the ground truth mesh you provided, leading to failed ICP matching and resulting in an F-score close to 0. How can I evaluate the reconstruction performance of SplatAM using the ground truth meshes you provided? Could you please provide some assistance with this? Thank you very much!
![mesh](https://github.com/VladimirYugay/Gaussian-SLAM/assets/63114150/b98403a4-dfc3-43db-9a0e-e99cf73c23cf)

**Comment by VladimirYugay** [comment]
Hey there. Sorry for the late reply. In case the problem still persists, the only modification we did is that we transformed the relative poses from SplaTAM by the first ground-truth pose, and reconstructed the mesh afterward.
