### ISSUE TITLE
Run other code?

### ISSUE THREAD

**Issue by YIXIN-M** [VladimirYugay/Gaussian-SLAM#28]
How did I obtain the values of evaluation metrics such as PNSR, SSIM, and LPIPS for NICE-SLAM, Vox Fusion, ESLAM, Point SLAM, and SplaTAM * in the paper? I downloaded the corresponding source code from GitHub and ran it on my computer, but I couldn't obtain the specific values of these evaluation metrics.

**Comment by VladimirYugay** [comment]
Hey there. Thanks for your interest in our work. Some of the metrics we took from this [survey](https://arxiv.org/abs/2402.13255). Concurrent methods we ran ourselves. To obtain results we ran each method three times with the seeds 0, 1, 2 and averaged them out.

**Comment by YIXIN-M** [comment]
These ESLAM, Splatam, nice slam can run but cannot obtain specific values for evaluation metrics such as PNSR, SSIM, and LPIPS in papers. Point slam can obtain these values in the Replica dataset, but cannot in other datasets. Do you want to add code for evaluation metrics such as PNSR, SSIM, and LPIPS to these source codes?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VladimirYugay/Gaussian-SLAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月28日(星期五) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VladimirYugay/Gaussian-SLAM] Run other code? (Issue #28)





 
Hey there. Thanks for your interest in our work. Some of the metrics we took from this survey. Concurrent methods we ran ourselves. To obtain results we ran each method three times with the seeds 0, 1, 2 and averaged them out.

**Comment by VladimirYugay** [comment]
We didn't plan to add rendering evaluation code for other datasets.

**Comment by VladimirYugay** [comment]
Closing it for now. Feel free to re-open if you have any other questions!
