### ISSUE TITLE
Вы крутые

### ISSUE THREAD

**Issue by Lindsaydoodle** [VladimirYugay/Gaussian-SLAM#3]
Привет когда организация разрешить публикнуть код будет что-то на подобии 1click install и желательно для винды)?

**Comment by VladimirYugay** [comment]
Привет! Спасибо за интерес. 

1 клик и GS это обычно несовместимые понятия, потому что там куда модули и все такое неприятное. Более того, под винду хз, потому что мы ее не используем. 

Попробуем сделать все возможное, чтобы сделать все удобным, мб хаггин фейс. Но на винде на WSL2 точно будет работать, потому что на ней запускали уже.

**Comment by VladimirYugay** [comment]
Code released!
