### ISSUE TITLE
Question about the visualization reconstruction scene

### ISSUE THREAD

**Issue by Yoona12** [VladimirYugay/Gaussian-SLAM#31]
Thanks for your great work!
When seeing the video, it has a  picture of visualization reconstruction scene as following.
![image](https://github.com/user-attachments/assets/b2958b4b-c99e-42e5-8ce3-a8e0dc74c01a)

I visualize the reconstruction scene by SuperSplat, and the result is shown following.
![image](https://github.com/user-attachments/assets/ced98237-8678-4286-bd24-88e8292412fd)
There is a roof in the visualization of the scene，so i am confused about how to remove the roof and get the the visualization reconstruction scene as yours?
Looing forward to your reply!

**Comment by unique1i** [comment]
Hi, @Yoona12,

this is correct, when the fly-through video is made, the roof part is cropped for visualization purpose. You can use select and crop in supersplat to do the cropping.

**Comment by VladimirYugay** [comment]
Feel free to re-open if you have any other questions!
