### ISSUE TITLE
Determine when to start new submap

### ISSUE THREAD

**Issue by EmeryLee97** [VladimirYugay/Gaussian-SLAM#33]
Hi, thanks for the great work!
I notice in `exceeds_motion_thresholds`, you used Euler angles instead of angle axis to decide whether a new submap should be initialized. Could you please explain why you made this choice?

**Comment by VladimirYugay** [comment]
Hey there, thanks for your interest in our work.

We felt that this is more natural to do so - large motion covered ~ start new submap. We didn't ablate on that though. I also assume that both of those options could work similarly.
