### ISSUE TITLE
visualize

### ISSUE THREAD

**Issue by a3124182425** [VladimirYugay/Gaussian-SLAM#34]
Hello, I would like to know how to visualize the results in 3D

**Comment by unique1i** [comment]
Hi. If you mean the final reconstruction results after the slam, we save reconstructed mesh in `mesh/final_mesh.ply`, and the gaussian splats in another ply file `<scene_name>_global_map.ply`.

**Comment by VladimirYugay** [comment]
Feel free to re-open if you have any further questions!
