### ISSUE TITLE
Replica-SLAM

### ISSUE THREAD

**Issue by chenqi13814529300** [VladimirYugay/Gaussian-SLAM#35]
git clone https://huggingface.co/datasets/voviktyl/Replica-SLAM
Download Replica-SLAM data, inside the png and jpg image damage, can not open.
![image](https://github.com/user-attachments/assets/aa5ecfc5-7b74-4ff0-8ac9-3c7a27d8aa84)

**Comment by VladimirYugay** [comment]
Thanks for your interest in our work.

Can you try `git lfs install` and git clone again?

**Comment by chenqi13814529300** [comment]
Thanks!!!

**Comment by VladimirYugay** [comment]
Feel free to re-open if you have any other questions!
