### ISSUE TITLE
default rgbd_dataset_freiburg1_desk.yaml

### ISSUE THREAD

**Issue by chenqi13814529300** [VladimirYugay/Gaussian-SLAM#36]
![image](https://github.com/user-attachments/assets/9bca7488-fee6-4375-beee-2c790eb52ec2)
It seems to have turned out a little poorly.

**Comment by VladimirYugay** [comment]
Hey there,

Can you please post PSNR and ATE? Also, keep in mind, that for TUM many regions are unobserved and the depth map quality is poor. This leads to artifacts caused by a single-view SLAM setup.

**Comment by VladimirYugay** [comment]
Feel free to re-open if you have any further questions!
