### ISSUE TITLE
Wrong config settings

### ISSUE THREAD

**Issue by EmeryLee97** [VladimirYugay/Gaussian-SLAM#42]
Hi, your config settings of TUM-RGBD fr3/office seems to be wrong.

https://github.com/VladimirYugay/Gaussian-SLAM/blob/main/configs/TUM_RGBD/rgbd_dataset_freiburg3_long_office_household.yaml
https://github.com/VladimirYugay/Gaussian-SLAM/blob/main/configs/TUM_RGBD/rgbd_dataset_freiburg1_desk.yaml

https://cvg.cit.tum.de/data/datasets/rgbd-dataset/file_formats#intrinsic_camera_calibration_of_the_kinect

**Comment by VladimirYugay** [comment]
Thanks for your interest in our work and for spotting this! We will double-check whether experiments are affected and update the configs!
