### ISSUE TITLE
Outdoor Dataset

### ISSUE THREAD

**Issue by FraDePace** [VladimirYugay/Gaussian-SLAM#43]
Hello, thanks a lot for your project!

I would like to know whether Gaussian-SLAM would work or not with an outdoor dataset (like images from a drone).

Thanks!

**Comment by VladimirYugay** [comment]
Thanks for your interest in our work! We never tested it outdoors. However, the quality of the RGB and depth images is the most important. The more blurry and incomplete they are, the worse the tracking.

**Comment by FraDePace** [comment]
ah ok thanks!
