### ISSUE TITLE
Update Project Page Link on Readme

### ISSUE THREAD

**Issue by Nik-V9** [VladimirYugay/Gaussian-SLAM#8]
Hey guys, congrats on the code release!

The project page link on the Readme points to SplaTAM. You might want to change that 😉

**Comment by Atticuszz** [comment]
> Hey guys, congrats on the code release!
> 
> The project page link on the Readme points to SplaTAM. You might want to change that 😉

hhhh
I do find it as well

**Comment by Tianci-Wen** [comment]
hhh, I thought I was dazzled and clicked on it many times.

**Comment by VladimirYugay** [comment]
Your readme was too good guys, sorry😂
